[workspace]
members = [
    "shared",
    "stream_finder",
    "chat_poller",
    "chat_manager",
    "detector",
    "alkonost",
    "ui"
]

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
opt-level = 'z'